# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/avnet-digilent-zedboard-2019.1.xdc

# Block Designs: bd/zed/zed.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed || ORIG_REF_NAME==zed} -quiet] -quiet

# IP: bd/zed/ip/zed_processing_system7_1_0/zed_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_processing_system7_1_0 || ORIG_REF_NAME==zed_processing_system7_1_0} -quiet] -quiet

# IP: bd/zed/ip/zed_btns_5bits_0/zed_btns_5bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_btns_5bits_0 || ORIG_REF_NAME==zed_btns_5bits_0} -quiet] -quiet

# IP: bd/zed/ip/zed_xbar_0/zed_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_xbar_0 || ORIG_REF_NAME==zed_xbar_0} -quiet] -quiet

# IP: bd/zed/ip/zed_ps7_1_axi_periph_0/zed_ps7_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_ps7_1_axi_periph_0 || ORIG_REF_NAME==zed_ps7_1_axi_periph_0} -quiet] -quiet

# IP: bd/zed/ip/zed_rst_ps7_1_100M_0/zed_rst_ps7_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_rst_ps7_1_100M_0 || ORIG_REF_NAME==zed_rst_ps7_1_100M_0} -quiet] -quiet

# IP: bd/zed/ip/zed_leds_8bits_0/zed_leds_8bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_leds_8bits_0 || ORIG_REF_NAME==zed_leds_8bits_0} -quiet] -quiet

# IP: bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_sws_8bits_0 || ORIG_REF_NAME==zed_sws_8bits_0} -quiet] -quiet

# IP: bd/zed/ip/zed_xlconstant_0_0/zed_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_xlconstant_0_0 || ORIG_REF_NAME==zed_xlconstant_0_0} -quiet] -quiet

# IP: bd/zed/ip/zed_auto_pc_0/zed_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_auto_pc_0 || ORIG_REF_NAME==zed_auto_pc_0} -quiet] -quiet

# XDC: bd/zed/zed_ooc.xdc
