# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.cache/wt [current_project]
set_property parent.project_path /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/imports/hdl/zed_wrapper.v
add_files /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/zed.bd
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_processing_system7_1_0/zed_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_btns_5bits_0/zed_btns_5bits_0_board.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_btns_5bits_0/zed_btns_5bits_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_btns_5bits_0/zed_btns_5bits_0.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_xbar_0/zed_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_rst_ps7_1_100M_0/zed_rst_ps7_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_rst_ps7_1_100M_0/zed_rst_ps7_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_rst_ps7_1_100M_0/zed_rst_ps7_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_leds_8bits_0/zed_leds_8bits_0_board.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_leds_8bits_0/zed_leds_8bits_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_leds_8bits_0/zed_leds_8bits_0.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_board.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_auto_pc_0/zed_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/zed_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/constrs_1/new/avnet-digilent-zedboard-2019.1.xdc
set_property used_in_implementation false [get_files /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/constrs_1/new/avnet-digilent-zedboard-2019.1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top zed_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zed_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zed_wrapper_utilization_synth.rpt -pb zed_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
