# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/training/git/avnet/hdl/Boards/PZ7010_FMC2/PZ7010_FMC2_i2c.xdc

# Block Designs: bd/pz_petalinux/pz_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux || ORIG_REF_NAME==pz_petalinux} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_processing_system7_0_0/pz_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_processing_system7_0_0 || ORIG_REF_NAME==pz_petalinux_processing_system7_0_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_axi_gpio_0_0/pz_petalinux_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_axi_gpio_0_0 || ORIG_REF_NAME==pz_petalinux_axi_gpio_0_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_axi_gpio_1_0/pz_petalinux_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_axi_gpio_1_0 || ORIG_REF_NAME==pz_petalinux_axi_gpio_1_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_xbar_0/pz_petalinux_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_xbar_0 || ORIG_REF_NAME==pz_petalinux_xbar_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_auto_pc_0/pz_petalinux_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_auto_pc_0 || ORIG_REF_NAME==pz_petalinux_auto_pc_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_ps7_0_axi_periph_0/pz_petalinux_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_ps7_0_axi_periph_0 || ORIG_REF_NAME==pz_petalinux_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_rst_ps7_0_100M_0 || ORIG_REF_NAME==pz_petalinux_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_xlconstant_0_0/pz_petalinux_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_xlconstant_0_0 || ORIG_REF_NAME==pz_petalinux_xlconstant_0_0} -quiet] -quiet

# IP: bd/pz_petalinux/ip/pz_petalinux_axi_iic_0_0/pz_petalinux_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_petalinux_axi_iic_0_0 || ORIG_REF_NAME==pz_petalinux_axi_iic_0_0} -quiet] -quiet

# XDC: bd/pz_petalinux/pz_petalinux_ooc.xdc
