# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0.xci
# IP: The module: 'pz_petalinux_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0.xci
# IP: The module: 'pz_petalinux_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/pz_petalinux/PZ7010_FMC2_2019_1/pz_petalinux.srcs/sources_1/bd/pz_petalinux/ip/pz_petalinux_rst_ps7_0_100M_0/pz_petalinux_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_petalinux_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
