# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xci
# IP: The module: 'zed_sws_8bits_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xci
# IP: The module: 'zed_sws_8bits_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /proj/petalinux/2019.1/petalinux-v2019.1_0522_1/logs/bsps/avnet-digilent-zedboard-2019.1/hw_proj/avnet-digilent-zedboard-2019.1/avnet-digilent-zedboard-2019.1.srcs/sources_1/bd/zed/ip/zed_sws_8bits_0/zed_sws_8bits_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_sws_8bits_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
